# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'XMLYDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'SVProgressHUD'
pod 'Alamofire', '~> 3.2.1'
pod 'SnapKit', '~> 0.19.1'
pod 'SDWebImage'
end
